name: Docker Build, Push & Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-push-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'my-flask-app'
          path: '.'
          format: 'HTML'
          out: 'reports' # this is the default, no need to specify unless you wish to override it
          args: >
            --failOnCVSS 7
            --enableRetired
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest .

      - name: Push Docker Image to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest

      - name: Install Syft for SBOM Generation
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sudo sh -s -- -b /usr/local/bin

      - name: Generate SBOM with Syft
        run: |
          syft ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest -o spdx-json > sbom.json

      - name: Upload SBOM as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SBOM Report
          path: sbom.json

      - name: Install Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sudo sh -s -- -b /usr/local/bin

      - name: Update Grype Database
        run: |
          grype db update

      - name: Pull Image from DockerHub
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest

      - name: Scan Docker Image with Grype
        run: |
          grype ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest

      - name: Install Trivy
        run: |
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_Linux-64bit.tar.gz
          tar -xzf trivy_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/
      
      - name: Scan Docker Image with Trivy
        run: |
          trivy image --exit-code 1 --severity HIGH,CRITICAL ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest

      - name: Upload Trivy Scan Report
        if: always()
        run: |
          trivy image --format json -o trivy-report.json ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest

      - name: Upload Trivy Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Trivy Scan Report
          path: trivy-report.json
